services:
  db:
    image: mysql:8.4
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_DATABASE: marketplace
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d:ro
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u$$MYSQL_USER -p$$MYSQL_PASSWORD || exit 1"]
      interval: 3s
      timeout: 2s
      retries: 40

  loader:
    build: ./loader
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: user
      DB_PASS: password
      DB_NAME: marketplace
      DATA_DIR: /data
    volumes:
      - ./data:/data:ro
    restart: "no"

  mongo:
    image: mongo:7
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express:1
    depends_on:
      - mongo
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo

  etl_mongo:
    build: ./etl_mongo
    depends_on:
      db:
        condition: service_healthy
      mongo:
        condition: service_started
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_USER: user
      MYSQL_PASS: password
      MYSQL_DB: marketplace
      MONGO_URI: mongodb://mongo:27017
      MONGO_DB: ssg
      MONGO_COLL: orders
    restart: "no"

volumes:
  db_data:
  mongo_data:
